### ISSUE TITLE
[BUG]: crash while adding a new server instance

### ISSUE THREAD

**Issue by thebino** [photos-network/android#93]
### Description of the bug

While adding a new server instance, the app is crashing with a NPE trying to extract the port from the input.

### Steps To Reproduce

1. Got to settings
2. Click on 'setup server instance'
3. Enter: https://demo.photos.network
4. 💥 boom

### Additional Information

```
06:33:35.034 AndroidRuntime     E  FATAL EXCEPTION: DefaultDispatcher-worker-3
                                   Process: photos.network.debug, PID: 13027
                                   java.lang.NullPointerException
                                   	at photos.network.data.settings.repository.SettingsRepositoryImpl.extractPort(SettingsRepositoryImpl.kt:127)
                                   	at photos.network.data.settings.repository.SettingsRepositoryImpl.access$extractPort(SettingsRepositoryImpl.kt:26)
                                   	at photos.network.data.settings.repository.SettingsRepositoryImpl$updateHost$2.invokeSuspend(SettingsRepositoryImpl.kt:92)
                                   	at photos.network.data.settings.repository.SettingsRepositoryImpl$updateHost$2.invoke(Unknown Source:12)
                                   	at photos.network.data.settings.repository.SettingsRepositoryImpl$updateHost$2.invoke(Unknown Source:10)
                                   	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                   	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
                                   	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                   	at photos.network.data.settings.repository.SettingsRepositoryImpl.updateHost(SettingsRepositoryImpl.kt:90)
                                   	at photos.network.domain.settings.usecase.UpdateHostUseCase.invoke(UpdateHostUseCase.kt:9)
                                   	at photos.network.settings.SettingsViewModel$updateHost$1.invokeSuspend(SettingsViewModel.kt:89)
                                   	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                   	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                   	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                   	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                   	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                   	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
                                   	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                   	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                   	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@36f7b29, Dispatchers.IO]
```

**Comment by thebino** [comment]
Still crashing

```
10:58:04.203 AndroidRuntime     E  FATAL EXCEPTION: DefaultDispatcher-worker-6
                                   Process: photos.network.debug, PID: 14552
                                   s9.i: Serializer for class 'a' is not found.
                                   Mark the class as @Serializable or provide the serializer explicitly.
                                   	at w9.y0.d(:91)
                                   	at w9.x0.k(:29)
                                   	at s9.l.e(:60)
                                   	at s9.k.c(:1)
                                   	at gc.b.k(:43)
                                   	at gc.b.d(:27)
                                   	at cc.c.h(:70)
                                   	at hc.d.i(:133)
                                   	at hc.d$d.i(:99)
                                   	at hc.d$d.m(Unknown Source:12)
                                   	at hc.d$d.T(Unknown Source:10)
                                   	at q9.b.b(:89)
                                   	at kotlinx.coroutines.l.e(:166)
                                   	at kotlinx.coroutines.j.g(:1)
                                   	at hc.d.c(:90)
                                   	at qc.d.b(:9)
                                   	at ad.i$c.i(:89)
                                   	at v8.a.K(:33)
                                   	at kotlinx.coroutines.g1.run(:106)
                                   	at kotlinx.coroutines.internal.q.run(:42)
                                   	at kotlinx.coroutines.scheduling.k.run(:95)
                                   	at kotlinx.coroutines.scheduling.a.E(:570)
                                   	at kotlinx.coroutines.scheduling.a$c.d(:749)
                                   	at kotlinx.coroutines.scheduling.a$c.n(:677)
                                   	at kotlinx.coroutines.scheduling.a$c.run(:664)
                                   	Suppressed: kotlinx.coroutines.e1: [b3{Cancelling}@5eb3ca4, Dispatchers.IO]
```
